spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
      jdbc:
        time_zone: ${TZ}
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data-prod.sql

logging:
  level:
    root: ERROR
    taco.klkl: WARN
    org.springframework: ERROR
    org.hibernate: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"