spring:
  config:
    activate:
      on-profile: "jwt"
jwt:
  secret: ${JWT_SECRET}
  redirect: ${JWT_REDIRECT_URI}
  expiration:
    access: ${ACCESS_TOKEN_EXPIRATION_TIME}
    refresh: ${REFRESH_TOKEN_EXPIRATION_TIME}